### ISSUE TITLE
Readme not correct?

### ISSUE THREAD

**Issue by dietmarw** [jlord/gs2geojson#2]
Hi I just followed the readme to get started. However that does not seem to be quite right:
- The command to invoke the tools is `.bin/gs2geojson` and not `gogogeo` on my machine (after having followed the instructions)

Either I'm doing something horrible wrong or the Readme simply needs to be updated.

**Comment by jlord** [comment]
Sorry about that! You are totally right. I had changed it a couple times in development and messed up the docs. It's updated now so give it ago. Thanks!

**Comment by dietmarw** [comment]
Great thanks for the fix.
